Repository Krafton-Jungle-Team6/Jungle-Mini-Poject, pull requests merged in 2022-10, with the labels that each got.

#1 메인페이지 이미지 하단으로 내림
  templates/index.html
Labels: Jeonje

#4 Login
  .vscode/launch.json
  app.py
  tempCodeRunnerFile.py
  templates/index.html
Labels: Inha

#5 아이피 제거
  app.py
  tempCodeRunnerFile.py
  templates/register.html
Labels: Jeonje

#6 [회원가입] flask, register.html 작성
  app.py
  tempCodeRunnerFile.py
  templates/index.html
  templates/register.html
Labels: Jeonje

#10 pull 후 참여 부분 flask commit
  app.py
  tempCodeRunnerFile.py
  templates/home.html
  templates/index.html
  templates/register.html
Labels: Jeonje

#11 Recovery
  app.py
Labels: Inha

#12 party join & party cancel in flask
  app.py
  tempCodeRunnerFile.py
  templates/home.html
  templates/test.html
Labels: Jeonje

#13 Feat: Edit main view
  app.py
  static/image/chinese_food.png
  static/image/japanese_food.png
  static/image/korean_food.png
  static/image/rice_logo.png
  static/image/western_food.jpg
  templates/home.html
  templates/index.html
  templates/test.html
Labels: Sugyeong

#14 Feat: create party
  app.py
  static/image/western_food.png
  templates/home.html
Labels: Sugyeong

#15 after party merge & add truncate
  app.py
  templates/home.html
Labels: Jeonje

#16 Merging Project
  app.py
  templates/home.html
Labels: Inha

#18 Check token in app
  app.py
  templates/home.html
Labels: Inha

#22 delete logs,prints
  templates/home.html
  templates/index.html
  templates/modify.html
  templates/register.html
  templates/test.html
Labels: Inha

#23 modify regExp
  app.py
  daily_delete.py
  tempCodeRunnerFile.py
  templates/modify.html
  templates/register.html
Labels: Jeonje

#25 check merge
  app.py
  templates/home.html
Labels: Inha

#26 pr
  templates/home.html
  templates/register.html
Labels: Jeonje

#29 client side inform check add
  app.py
  templates/register.html
Labels: Jeonje

#31 최종 전 점검
  app.py
  templates/home.html
  templates/index.html
  templates/modify.html
  templates/register.html
  templates/test.html
Labels: Sugyeong

#33 delete party alert modify
  templates/home.html
Labels: Jeonje

#35 alert modify
  templates/index.html
  templates/modify.html
Labels: Jeonje
